### ISSUE TITLE
Updates to Identity System

### ISSUE THREAD

**Issue by Gramps** [LauraWebdev/GodotSteam_CSharpBindings#34]
Recently we removed the identity system in GodotSteam and replaced it with Steam IDs.  Not sure what it takes to make those changes in this.

If you can point me in the right directions of the files that need changed, I can probably figure it out and issue a PR.

**Comment by Avantir-Chaosfire** [comment]
@Gramps I got tired of waiting and looked into it myself, and it turned out to be much easier than I anticipated. Tested it and it worked. Unfortunately I don't think I have permission on this repo to create a branch or PR... So here is the full zip of this repo with my changes (not sure how to export a commit as a file, and not interested in figuring it out right now).

[NetworkingIdentityToSteamId.zip](https://github.com/user-attachments/files/16114492/NetworkingIdentityToSteamId.zip)

I suggest incorporating this into GodotSteam proper, as it seems useful and easy to maintain, and it seems this repo isn't being maintained anymore...

**Comment by LauraWebdev** [comment]
@Avantir-Chaosfire I am still mainting this addon, however I've been working on a bigger update which changes a lot more but is not ready to be merged yet. I have ported and merged your changes for the time being.

**Comment by Gramps** [comment]
@LauraWebdev We discussed this a bit in Discord but if there is something I can do to help, let me know.  Like if there is a way to parse GodotSteam's C++ files much like Riley does for Steamworks.NET or perhaps there is some way I can contribute changes to this when I make them for GodotSteam.
